tap "hashicorp/tap"
tap "elastic/oblt-cli"

brew "coreutils"
brew "direnv"
brew "elastic/oblt-cli/oblt-cli"
brew "findutils"
brew "gh"
brew "hashicorp/tap/vault"
brew "helm"
brew "minikube"
brew "nvm"
brew "ollama"
brew "openjdk"
brew "rg"
brew "shellcheck"
brew "terraform"
brew "uv"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
# cask "cleanshot" # Homebrew installs Cleanshot X but I have 2.x
cask "cursor"
cask "docker-desktop"
cask "font-monaspace"
cask "google-drive"
cask "harvest"
cask "microsoft-edge"
cask "pixelsnap"
cask "slack"
cask "visual-studio-code"
cask "zoom"

