brew "coreutils"
brew "direnv"
brew "findutils"
brew "gh"
brew "minikube"
brew "nvm"
brew "shellcheck"

cask "1password"
# cask "cleanshot" # Homebrew installs Cleanshot X but I have 2.x
cask "docker-desktop"
cask "font-monaspace"
cask "google-drive"
cask "harvest"
cask "microsoft-edge"
cask "pixelsnap"
cask "slack"
cask "visual-studio-code"
