export EDITOR=vim
export PATH=./node_modules/.bin:$HOME/bin:$HOME/.rbenv/shims:/usr/local/bin:/usr/local/sbin:$PATH
export NODE_PATH=./node_modules:$HOME/.node_modules:/usr/local/lib/node_modules:$NODE_PATH

# Load .bashrc
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

# ls alias and color, open alias
if [ `uname` == "Darwin" ]; then
  export LSCOLORS=Dxfxcxdxbxegedabagacad
  alias ls="ls -FGh"
  alias o="open"
else
  alias ls="ls -Fh --color=auto"
  alias o="vim"
fi

# Alias mvim (MacVim) to vim and make EDITOR if available
if [ `command -v mvim 2> /dev/null` ]; then
  alias vi="mvim -v"
  alias vim="mvim -v"
  export EDITOR="mvim -v"
fi

# Ubuntu calls ack ack-grep.
if [ `command -v ack-grep 2> /dev/null` ]; then
  alias ack="ack-grep"
fi

# Use pydf if it's available
if [ `command -v pydf 2> /dev/null` ]; then
  alias df="pydf"
fi

# Lisp stuff
if [ `command -v clj 2> /dev/null` ]; then
  alias lisp="rlwrap clj"
fi

# Ruby tweaks (see https://gist.github.com/1688857)
export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_HEAP_FREE_MIN=500000

# rbenv
if [ `command -v rbenv 2> /dev/null` ]; then
  eval "$(rbenv init -)"
fi

# Git Situational Awareness
[[ -s "$HOME/.git_sit_awareness.sh" ]] && source "$HOME/.git_sit_awareness.sh"
