# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim
export PATH=./node_modules/.bin:$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH
export NODE_PATH=./node_modules:$HOME/.node_modules:/usr/local/lib/node_modules:$NODE_PATH

# Alias mvim (MacVim) to vim and make EDITOR if available
if [ `command -v mvim 2> /dev/null` ]; then
  alias vim="mvim"
  export EDITOR="mvim -f"
  export GEM_EDITOR="open" # This is for the gem-open gem on a Mac
fi

# ls alias and color, open alias
if [ `uname` = "Darwin" ]; then
  alias ls="ls -FGh"
  alias o="open"
else
  alias ls="ls -Fh --color=auto"
  alias o="vim"
fi

# Ubuntu calls ack ack-grep.
if [ `command -v ack-grep 2> /dev/null` ]; then
  alias ack="ack-grep"
fi

# Use pydf if it's available
if [ `command -v pydf 2> /dev/null` ]; then
  alias df="pydf"
else
  alias df="df -h"
fi

# Load RVM into a shell session
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Source the current directory's .rvmrc if it has one
[[ -s ".rvmrc" ]] && . ".rvmrc"
