# The following lines were added by Docker Desktop to add commands to your PATH.
export PATH="$PATH:/Users/smith/.docker/bin"
# End of Docker Desktop section.

eval "$(/opt/homebrew/bin/brew shellenv zsh)"
